FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash ca-certificates curl \
    default-mysql-client \
    gzip coreutils findutils \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /backup
COPY backup.sh /backup/backup.sh
RUN chmod +x /backup/backup.sh

ENTRYPOINT ["/bin/bash","-lc"]
CMD ["/backup/backup.sh"]
