{
 "title": "MedAssist - RED (API)",
 "tags": [
  "medassist",
  "red",
  "api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{job=\"api\"}[2m])) or sum(rate(flask_http_request_total{job=\"api\"}[2m])))"
    }
   ]
  },
  {
   "title": "Errors (5xx %)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ((sum(rate(http_requests_total{job=\"api\",status=~\"5..\"}[5m])) or sum(rate(flask_http_request_total{job=\"api\",status=~\"5..\"}[5m]))) / (sum(rate(http_requests_total{job=\"api\"}[5m])) or sum(rate(flask_http_request_total{job=\"api\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Duration p95 (s)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"api\"}[5m])) by (le))) or (histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket{job=\"api\"}[5m])) by (le))))"
    }
   ]
  }
 ]
}