server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }

  # API via HAProxy
  location /api/ {
    proxy_pass http://haproxy:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
